version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9000:9000"
    networks:
      - iron-network

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://api:9000
    depends_on:
      - api
    networks:
      - iron-network

networks:
  iron-network:
    driver: bridge